//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandIprojects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBenefit
    {
        public int EmployeeBenefitId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> BenefitId { get; set; }
    
        public virtual Benefit Benefit { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
